// Build stamp — regenerated by the Build Library (.NET) workflow; Build 0 means a local build.
namespace HeatonLife
{
    /// <summary>Version and build stamp of this HeatonLife.Core assembly.</summary>
    public static class HeatonLifeVersion
    {
        public const string Version = "1.0.0";
        public const string BuildDate = "";
        public const int Build = 0;
    }
}
